language: java
install: DISPLAY=:99.0 mvn install -Dgpg.skip=true
addons:
  firefox: "latest-esr"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
notifications:
  email:
  - mathieu.goulin@gadz.org
