language: java
jdk:
- oraclejdk8
env:
  global:
  - SONATYPE_USERNAME=matgou
  - secure: BFjRMVDx6eF3yATDumAxlb2WtJrNV228OgFIpuzBo+wbX72B49tCsJJ+kQorsvH2rJnCf7qvvD5pfNzMtbWJL3roZZscXmoPxRq4SSMY2KCHwzno8hq5VmCjSVgrbB+DtknJVI+CidLoHhWxBSk5SoYd/bkaYof8JPSjYrGv8uo=
addons:
  firefox: latest-esr
before_install:
- gpg --import < travis.gpg
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
install: DISPLAY=:99.0 mvn install -Dgpg.skip=true
notifications:
  email:
  - mathieu.goulin@gadz.org
after_success:
- python addServer.py
- mvn clean deploy --settings settings.xml

before_deploy:
- mvn -Dmaven.test.skip=true package install
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Q+J8CmF3o28/VMg6BP40vaofduJfEWRHDA1c6aZiJqCx/CjZdis4JjUXYJ6V6H9EI5SuxxD5zlHrOoZQZOqzhR+n3i0Aevg+TAYfBqiEpFJBmCZfEocIiiprAA+GPLYqICq5v2a5DbbOCIkSyH1IB2nWKqxVZQ4mcsxlHdtBM9k=
  file: target/batch_run.jar-jar-with-dependencies.jar
  on:
    repo: matgou/AutomationScenarioAPI
